USE surf_the_task;

ALTER TABLE reminders
  MODIFY COLUMN reminder_type ENUM(
    'AVAILABILITY_BASED',
    'DEADLINE_WARNING',
    'OVERDUE_ALERT',
    'DELAYED_IN_SITE',
    'DAILY_GOAL_DAY_END_ONE_HOUR',
    'DAILY_GOAL_DAY_END_THIRTY_MINUTES',
    'DEADLINE_ONE_HOUR',
    'DEADLINE_THIRTY_MINUTES'
  ) NOT NULL;
